### PR TITLE
Docopt 0.6.2 compat squashed

### PR DESCRIPTION
**Pull request by NickCrews**
Squashed version of #36

### CODE REVIEW

**Comment by NickCrews** [comment]
@h4l is this good to be merged?

**Comment by h4l** [comment]
@NickCrews Yes, all good for me, just as long as you're good with the option description fix https://github.com/jazzband/docopt-ng/pull/36#issuecomment-1240357546

**Comment by h4l** [comment]
OK, that's it rebased on the current master. Could also force push this to the existing branch to merge that PR if you like. I think you've got permission to do that if you want to.

**Comment by NickCrews** [comment]
Superseded by the merged #36

**Pull request closed without merging**
