### PR TITLE
 Include arument type infomation in option class, closes issue #3

### LINKED ISSUE #3: Provide option metadata
For the following option definition
```
-c --count=<int>    Option for a count of some kind [default: 42] 
```
Is there a way to retrieve the default value ( `42`) and the value of the value designation (`<int>`) programatically? I.e. is the a way to get from the resulting `args` after docopt-ng is done parsing? I have an oustanding [PR in original docopt](https://github.com/docopt/docopt/pull/346) for that sort of change but, as well all know, that's not going to be merged.

### PR DESCRIPTION
**Pull request by con-f-use**
This PR makes argument validation easier by parsing argument types and making them accessible, if provided in the docstring.

E.g. merging this Pull request makes this possible:

```python
"""Some stuff

Usage:
    {__package__} [options]

Options:
    -s --speed=<float>    Speed in km/h [default: 42]
    --count=<posint>      How often [default: 1]

"""
__doc__ = __doc__.format(**globals())


from docopt import docopt, parse_defaults


def convert_arg(atype, value):
    if atype == '<float>':
        return float(value)
    elif atype == '<posint>':
        value = int(value)
        if value < 0:
            raise ValueError('Must be positive integer!')
        return value
    return value


if __name__ == '__main__':
    args = docopt(__doc__, version="Dei mama hat a version!")
    atypes = {(o.longer or o.short):o.atype for o in parse_defaults(__doc__)}

    for key, value in args.items():
        if key in atypes:
            args[key] = convert_arg(atypes[key], value)

    print(args)
```
In action:
```
┌─11-18:15[con-f-use@confusion6:~/devel/docopt-ng] $ 
└▪ python playground.py
{'--count': 1,
    '--speed': 42.0}
┌─11-18:16[con-f-use@confusion6:~/devel/docopt-ng] $ 
└▪ python playground.py --count -1
Traceback (most recent call last):
    File "playground.py", line 35, in <module>
    args[key] = convert_arg(atypes[key], value)
    File "playground.py", line 24, in convert_arg
    raise ValueError('Must be positive integer!')
ValueError: Must be positive integer!
```
Note how `--count` and `--speed` are actual number types as opposed to strings.

see: https://github.com/bazaar-projects/docopt-ng/issues/3

### CODE REVIEW

**Comment by con-f-use** [comment]
@itdaniher did this project go the way of original docopt?

**Comment by cjwelborn** [comment]
@con-f-use, Do the types have to be strings? I haven't looked at this, but could we do `if isinstance(style, float)` instead? That opens up a whole lot of possibilities of we have access to the actual class, instead of just a string with the class name in it. Just a thought, correct me if I'm way off base.

**Comment by con-f-use** [comment]
Well, the way that arguments are specified in the doc string these "types" are arbitrary strings and do not have to match an existing class from Python. I.e. the user specifies them in the docstring like this:
```
Docstring.

Options:
    -s --speed=<float>    Speed in km/h [default: 42]
```
but they could just as well write:
```
Options:
    -s --speed=<wooseldoosel>    Speed in km/h [default: 42]
```
without docopt complaining. 

Nonetheless, I find this information useful and my pull request wants to make it more accessible, so parsing can use it.

It would be pretty trivial to look for existing class and substitute the string value for the actual class if one is found. Not the scope of this PR though and docopt is more flexible if they remain strings and users write additional code for that (the way my example shows) if they need it.

**Comment by cjwelborn** [comment]
Yeh, after I read the actual PR I saw that it was just part of the doc string. I spoke too soon. I think itdaniher was talking about merging this in issue #4. I'm looking forward to it.

**Comment by NickCrews** [comment]
Hey there @con-f-use @cjwelborn, I've picked this project up as a new maintainer.

At this point, I don't feel comfortable merging this. Sorry that you've both in in some effort here, but here are my reasons:
- I'd like to see some other people express interest in this. If you like this feature request, give the original post a thumbs up
- This is drifting away from the original spec outlined at docopt.org. Ideally I'd like this fork, since it has been picked up by jazzband, to become the canonical version, so I want to be judicious with what features we add.
- At first glance (I haven't tried I'll admit) this seems to be not too difficult to implement yourself.

Do those concerns make sense?

**Comment by con-f-use** [comment]
I can live with that, just consider two things:

1. The problem with your snipped is, that the information is duplicated and can get out of sync. Also docopt's whole stick is, that the entire command line interface is specified in the docstring, hence self-documenting.

image

2. Not sure, but you seem to think that the `--long-opt=<type>` notation is not part of the spec. It is, however, [mentioned](https://github.com/docopt/docopt/blame/master/README.rst#L361) in many places in the original docopt documentaiton. Also, is POSIX and docopt claims to follow POSIX.

image

**Comment by h4l** [comment]
FWIW, as a docopt user, I value that docopt itself is super-simple. I get that you'd like to keep validation rules in-sync with the usage, but ultimately the usage text isn't rich enough to encode realistic validation rules in the general case. Sure, you can say something's a float, but as soon as it has to be in a certain range, or be constrained by the value of another option you're going to have to define extra validation rules outside the usage text.

IMO it's better to just let docopt stay focussed on parsing the arguments, and handle validation as a second step, using whatever method seems best. Personally I've had good results from using Pydantic to define a model of my arguments, and using it to validate the dict that docopt creates. That also gives you a sensible type to pass around.

**Comment by con-f-use** [comment]
This PR does not implement any validation, it just gives easy structured access to the information in the docstring.

**Comment by h4l** [comment]
Sure. In my reply I was thinking of what you said here:
> The problem with your snipped is, that the information is duplicated and can get out of sync.

Unless I'm misunderstanding, what you're providing with `atype` is the second part of an option, e.g. with `--foo=<bar>`, `atype` is the string `"<bar>"`.

My feeling is that having access to `atype` can't actually solve this problem of duplicated/out-of-sync information. Because just knowing the `atype` of a value isn't enough by itself to validate it in the general case, we'll always need additional context which can't be encoded in the usage string.

For example:

```
usage: random_number [--min=<int>] [--max=<int>]
```

Knowing that a `atype` is `<int>` can't prevent the `--min` value from being greater than the `--max` value. So to validate this I'd need to have something defined outside the usage string which knows about the relationship between these values, hence something that can get out of sync with the usage string, regardless of having `atype` or not.

Also, I'm not sure that `atype` is the right name for what this provides. It's something like the name of an option's value, not necessarily a type. e.g. `--from=<start>` `--to=<end>`.

**Comment by NickCrews** [comment]
> Not sure, but you seem to think that the --long-opt=<type> notation is not part of the spec

Sorry, I wasn't super precise here upon re-reading what I wrote. You're right in the sense that this feature is part of the spec in the sense that it *would not violate it*. I mean it's not part of the spec in the sense that *it isn't a documented feature*. If something is supported, then I believe that it should be fully documented. If something isn't documented, then I don't think it should exist. I don't like secret features that are there for some people to discover.

>  the usage text isn't rich enough to encode realistic validation rules in the general case

These are some great points, but I think *this* is the really big sticking point for me.

> This PR does not implement any validation, it just gives easy structured access to the information that's already in the docstring

I don't get what having this information gains you? You're not saving any indirection anywhere, you either are going to have to have the mapping of `"<posint>"` -> `to_pos_int` (what this PR allows), or you have the mapping `"--speed"` -> `to_pos_int` (what we have right now, and in fact I think I prefer this one, it's more explicit).

I'm still not going to merge this at this point, but will leave it open.

**Comment by bittner** [comment]
Just as a heads-up, I'm interested in this feature (as in: display default values and the expected type). I'd also like to see type validation and having a [choices](https://docs.python.org/3/library/argparse.html#choices) list type.

> This is drifting away from the original spec outlined at docopt.org.

@NickCrews Can you elaborate what is the "original spec" and why adding types and default values make us drift away from it?

In the meantime, I'm going to evaluate [type-docopt](https://pypi.org/project/type-docopt/), which seems to do it all, but I'm not sure yet whether that works with docopt-ng.

**Comment by NickCrews** [comment]
> @NickCrews Can you elaborate what is the "original spec" and why adding types and default values make us drift away from it?

Hi! Good to hear that someone else wants this. Please, if you want this as well, keep chiming in, it is evidence that leads me to reconsider.

By "original spec" I mean the one published at [docopt.org](https://www.docopt.org), which has become canonical as there are many [other language forks]( https://github.com/docopt) that have implemented that. By "drift away", I meant same as what I said above:

> it's not part of the spec in the sense that it isn't a documented feature. If something is supported, then I believe that it should be fully documented. If something isn't documented, then I don't think it should exist. I don't like secret features that are there for some people to discover.  It makes things confusing to the users, if this project works differently than what docopt.org says. It would be hard to change docopt.org because we would need to build consensus between all the languages on what they want, then get write access from the current owner.

Does that make sense? Think I'm missing something?

**Comment by NickCrews** [comment]
I'm going to close this as wontfix, because of

1. inability to do complete validation.
2. drift away from the original spec, which would cause confusion.

I'm sorry and I understand if people find this frustrating. Any new CLI work should be using a more modern CLI library I think, I just want docopt to stick around enough that people's ancient scripts will continue to work.

**Pull request closed without merging**
